---
type: "lagged_controller"
history: 2
steps: 1
dt: 0.1
noise:
  - - 100.
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 100.
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 100.
    - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
    - 100
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 100
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 100.